services:
  postgres-dev:
    image: postgres:16
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_pass
      POSTGRES_DB: task_core_dev
    ports:
      - "5433:5432"
    volumes:
      - task_pg_dev:/var/lib/postgresql/data
      - ../db/init/dev.sql:/docker-entrypoint-initdb.d/init.sql
      - ../db/schema.sql:/schema.sql
    restart: unless-stopped

volumes:
  task_pg_dev: